apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: 2000m
    requests.memory: 1Gi
    limits.cpu: 2000m
    limits.memory: 2Gi
    requests.nvidia.com/gpu: 4
