apiVersion: apps/v1
kind: Deployment
metadata:
  name: ais-ifm
  labels:
    product: actimize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ais
      tier: web
  template:
    metadata:
      labels:
        app: ais
        tier: web
    spec:
      containers:
      - name: bootcamp-container
        image: jocatalin/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 200Mi
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
