apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-server
  labels:
    product: actimize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      tier: web
  template:
    metadata:
      labels:
        app: jenkins
        tier: web
    spec:
      containers:
      - name: jen-container
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1000m
            memory: 600Mi
          requests:
            cpu: 200m
            memory: 200Mi
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 400m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
